server:
  port: 8082



spring:
  banner:
    location: classpath:banner/banner.txt
#    application:
#      name: B2B-provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spookify?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#      cloud:
#        stream:
#          binders:
#            defaultRabbit:
#              type: rabbit
#              environment:
#                spring:
#                  rabbitmq:
#                    host: 10.72.221.48
#                    port: 5673
#                    username: guest
#                    password: guest
#          bindings:
#            input:
#              destination: studyExchange
#              content-type: application/json
#              binder: defaultRabbit
#              group: qiu
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_empty




